### ISSUE TITLE
Frogatto sometimes gets stuck in a weird, bad state after teleporting.

### ISSUE THREAD

**Issue by DDR0** [frogatto/frogatto#376]
When loading up [save2.cfg](https://github.com/frogatto/frogatto/files/2108674/save2.cfg.txt) and entering the teleporter, Bad Things Happen™. There are two symptoms, depending on if you're in the editor or out of the editor when you teleport to a pedestal from the world map.

**Out of the editor:**
The game crashes. See [log.txt](https://github.com/frogatto/frogatto/files/2108675/log.txt) for details. The backtrace from that:
```
#0  0x0000000000000000 in ?? ()
#1  0x00005555560481ff in LevelRunner::play_cycle (this=this@entry=0x7fffffffd580)
    at src/level_runner.cpp:1087
#2  0x000055555604d48a in LevelRunner::play_level (this=0x7fffffffd580) at src/level_runner.cpp:892
#3  0x00005555558c7596 in main (argcount=<optimised out>, argvec=<optimised out>)
    at src/main.cpp:1230
```

**In the editor:**
Frogatto successfully spawns, gets added to the level, but is variably functional. In the best case, he can move and spawns a shadow but he is invisible. This is fixed when entering a different level by running off-screen left or right. In the worst case, he is completely unresponsive. In either case, his opacity—which is set on line 62 of `map_selector.cfg` as `set(_player.alpha, 0),`—is settable and appears normal, but does not influence how Frogatto is rendered on-screen. Modifying line 62 to `set(_player.alpha, 120),` results in a transparent frog who will still resist all attempts at corporeality.

I strongly suspect something is going off the rails line 65 of `map_selector.cfg`, `add_object(_player),`. If the player is spawned, as on line 69, everything seems to work as it should.

**Comment by DDR0** [comment]
Fixed by Dave's e3be51f62.
