### ISSUE TITLE
Unable to boot the game before manual edit of preference.

### ISSUE THREAD

**Issue by ghost** [frogatto/frogatto#379]
Boot (`master`), activate a (the) CJK language, hang around, close the game.
Anyhow your stored preference for `locale` is`zh_CN`. Try to boot, it won't, `ASSERTION FAILED: UNKNOWN FONT: numbers_gold_enormous`.

**Comment by DDR0** [comment]
Digging (a little bit) deeper, we get the following GDB backtrace:
```
(gdb) bt
#0  raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x000055555639ef4b in report_assert_msg (
    m="custom_object_functions.cpp:150 ASSERTION FAILED: custom_object.cpp:6004 ASSERTION FAILED: UNKNOWN FONT: numbers_gold_enormous\n\nERROR ENCOUNTERED WHILE RUNNING COMMAND GENERATED BY THIS EXPRESSION:\nUn"...) at src/asserts.cpp:138
#2  0x00005555561a16ff in CustomObjectCommandCallable::runCommand (
    this=this@entry=0x555560767be0, lvl=..., obj=...)
    at src/custom_object_functions.cpp:150
#3  0x0000555555de600f in CustomObject::executeCommand (this=this@entry=0x555560677530, 
    var=...) at src/custom_object.cpp:5642
#4  0x0000555555de5fd0 in CustomObject::executeCommand (this=0x555560677530, var=...)
    at src/custom_object.cpp:5633
#5  0x0000555555df2e94 in CustomObject::handleEventInternal (
    this=this@entry=0x555560677530, event=6, context=<optimized out>, 
    executeCommands_now=executeCommands_now@entry=true) at src/custom_object.cpp:5580
#6  0x0000555555df37c5 in CustomObject::handleEvent (this=0x555560677530, 
    event=<optimized out>, context=<optimized out>) at src/custom_object.cpp:5472
#7  0x0000555555deaede in CustomObject::createObject (this=0x555560677530)
    at src/custom_object.cpp:1689
#8  0x0000555556180633 in (anonymous namespace)::add_object_command::execute (
    this=0x5555607927d0, lvl=..., ob=...) at src/custom_object_functions.cpp:3379
#9  0x0000555555de604f in CustomObject::executeCommand (this=this@entry=0x5555605eb640, 
    var=...) at src/custom_object.cpp:5646
---Type <return> to continue, or q <return> to quit---
#10 0x0000555555de5fd0 in CustomObject::executeCommand (this=this@entry=0x5555605eb640, 
    var=...) at src/custom_object.cpp:5633
#11 0x0000555555de5fd0 in CustomObject::executeCommand (this=this@entry=0x5555605eb640, 
    var=...) at src/custom_object.cpp:5633
#12 0x0000555555de5fd0 in CustomObject::executeCommand (this=0x5555605eb640, var=...)
    at src/custom_object.cpp:5633
#13 0x0000555555ebeec9 in game_logic::(anonymous namespace)::CommandSequence::execute (
    this=0x555560767f40, ob=...) at src/formula.cpp:3034
#14 0x0000555555ec5841 in game_logic::CommandCallable::runCommand (this=0x555560767f40, 
    context=...) at src/formula.cpp:235
#15 0x0000555555de5f57 in CustomObject::executeCommand (this=this@entry=0x5555605eb640, 
    var=...) at src/custom_object.cpp:5638
#16 0x0000555555de5fd0 in CustomObject::executeCommand (this=this@entry=0x5555605eb640, 
    var=...) at src/custom_object.cpp:5633
#17 0x0000555555de5fd0 in CustomObject::executeCommand (this=this@entry=0x5555605eb640, 
    var=...) at src/custom_object.cpp:5633
#18 0x0000555555de5fd0 in CustomObject::executeCommand (this=0x5555605eb640, var=...)
    at src/custom_object.cpp:5633
#19 0x0000555555ebeec9 in game_logic::(anonymous namespace)::CommandSequence::execute (
    this=0x555560796200, ob=...) at src/formula.cpp:3034
#20 0x0000555555ec5841 in game_logic::CommandCallable::runCommand (this=0x555560796200, 
    context=...) at src/formula.cpp:235
#21 0x0000555555de5f57 in CustomObject::executeCommand (this=0x5555605eb640, var=...)
---Type <return> to continue, or q <return> to quit---
    at src/custom_object.cpp:5638
#22 0x0000555555ebef8a in game_logic::(anonymous namespace)::CommandSequence::execute (
    this=<optimized out>, ob=...) at src/formula.cpp:3043
#23 0x0000555555ec5841 in game_logic::CommandCallable::runCommand (this=0x555560767e40, 
    context=...) at src/formula.cpp:235
#24 0x0000555555de5f57 in CustomObject::executeCommand (this=0x5555605eb640, var=...)
    at src/custom_object.cpp:5638
#25 0x0000555555ebef8a in game_logic::(anonymous namespace)::CommandSequence::execute (
    this=<optimized out>, ob=...) at src/formula.cpp:3043
#26 0x0000555555ec5841 in game_logic::CommandCallable::runCommand (this=0x555560399290, 
    context=...) at src/formula.cpp:235
#27 0x0000555555de5f57 in CustomObject::executeCommand (this=this@entry=0x5555605eb640, 
    var=...) at src/custom_object.cpp:5638
#28 0x0000555555de5fd0 in CustomObject::executeCommand (this=0x5555605eb640, var=...)
    at src/custom_object.cpp:5633
#29 0x0000555555ec5809 in game_logic::CommandCallable::runCommand (this=0x55556074c470, 
    context=...) at src/formula.cpp:230
#30 0x0000555555de5f57 in CustomObject::executeCommand (this=this@entry=0x5555605eb640, 
    var=...) at src/custom_object.cpp:5638
#31 0x0000555555de5fd0 in CustomObject::executeCommand (this=0x5555605eb640, var=...)
    at src/custom_object.cpp:5633
#32 0x0000555555ebef8a in game_logic::(anonymous namespace)::CommandSequence::execute (
    this=<optimized out>, ob=...) at src/formula.cpp:3043
---Type <return> to continue, or q <return> to quit---
#33 0x0000555555ec5841 in game_logic::CommandCallable::runCommand (this=0x5555603998b0, 
    context=...) at src/formula.cpp:235
#34 0x0000555555de5f57 in CustomObject::executeCommand (this=this@entry=0x5555605eb640, 
    var=...) at src/custom_object.cpp:5638
#35 0x0000555555de5fd0 in CustomObject::executeCommand (this=0x5555605eb640, var=...)
    at src/custom_object.cpp:5633
#36 0x0000555555df2e94 in CustomObject::handleEventInternal (
    this=this@entry=0x5555605eb640, event=6, context=<optimized out>, 
    executeCommands_now=executeCommands_now@entry=true) at src/custom_object.cpp:5580
#37 0x0000555555df37c5 in CustomObject::handleEvent (this=0x5555605eb640, 
    event=<optimized out>, context=<optimized out>) at src/custom_object.cpp:5472
#38 0x0000555555deaede in CustomObject::createObject (this=0x5555605eb640)
    at src/custom_object.cpp:1689
#39 0x0000555555f59ee5 in Level::do_processing (this=this@entry=0x555560116ba0)
    at src/level.cpp:2766

#40 0x0000555555f5a0ae in Level::process (this=0x555560116ba0) at src/level.cpp:2649
#41 0x0000555555e5e52f in LevelRunner::play_cycle (this=this@entry=0x7fffffffd690)
    at src/level_runner.cpp:1740
#42 0x0000555555e63c9a in LevelRunner::play_level (this=0x7fffffffd690)
    at src/level_runner.cpp:892
#43 0x00005555558e7c46 in main (argcount=<optimized out>, argvec=<optimized out>)
    at src/main.cpp:1230
```
While I've had a poke at it, I'm not really familiar enough with GDB or C++ to figure out what object's causing the issue. I expect something around frame 38 might be useful. :man_shrugging:

**Comment by galegosimpatico** [comment]
This was not reproducible by 052d62221f48af5cd2239343937ea1fded84f2 by Yaohan in early september 2018. Please close as fixed.
